# Dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["cloud-atlas.csproj", "."]
RUN dotnet restore "./cloud-atlas.csproj"
COPY . .
RUN dotnet build "cloud-atlas.csproj" -c Release -o /app/build
RUN dotnet publish "cloud-atlas.csproj" -c Release -o /app/publish


FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
#COPY --from=migrations /app/migrations ./migrations
ENTRYPOINT ["dotnet", "cloud-atlas.dll"]