services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cloud-atlas-local
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sql_data:
