// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cloud_atlas;

#nullable disable

namespace cloud_atlas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250626153002_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cloud_atlas.Entities.Models.Atlas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Atlases");
                });

            modelBuilder.Entity("cloud_atlas.Entities.Models.AtlasUsers", b =>
                {
                    b.Property<Guid>("AtlasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit");

                    b.HasKey("AtlasId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AtlasUsers");
                });

            modelBuilder.Entity("cloud_atlas.Entities.Models.Marker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtlasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AtlasId");

                    b.ToTable("Markers");
                });

            modelBuilder.Entity("cloud_atlas.Entities.Models.PhotoDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MarkerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("URLs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarkerId");

                    b.ToTable("PhotoDetails");
                });

            modelBuilder.Entity("cloud_atlas.Entities.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("cloud_atlas.Entities.Models.AtlasUsers", b =>
                {
                    b.HasOne("cloud_atlas.Entities.Models.Atlas", null)
                        .WithMany("AtlasUsers")
                        .HasForeignKey("AtlasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cloud_atlas.Entities.Models.User", null)
                        .WithMany("AtlasUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("cloud_atlas.Entities.Models.Marker", b =>
                {
                    b.HasOne("cloud_atlas.Entities.Models.Atlas", "Atlas")
                        .WithMany("Markers")
                        .HasForeignKey("AtlasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atlas");
                });

            modelBuilder.Entity("cloud_atlas.Entities.Models.PhotoDetails", b =>
                {
                    b.HasOne("cloud_atlas.Entities.Models.Marker", "Marker")
                        .WithMany("Photos")
                        .HasForeignKey("MarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marker");
                });

            modelBuilder.Entity("cloud_atlas.Entities.Models.Atlas", b =>
                {
                    b.Navigation("AtlasUsers");

                    b.Navigation("Markers");
                });

            modelBuilder.Entity("cloud_atlas.Entities.Models.Marker", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("cloud_atlas.Entities.Models.User", b =>
                {
                    b.Navigation("AtlasUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
